package entity;
// default package
// Generated Feb 26, 2014 5:12:18 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name = "Brands", schema = "dbo", catalog = "warehouseDB1")
public class Brands implements Serializable {

	/** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int brandId;
	private String name;
	private Set<Products> productses = new HashSet<Products>(0);

	public Brands() {
	}

	public Brands(int brandId,String name) {
		this.brandId = brandId;
		this.name = name;
	}

	public Brands(int brandId,String name, Set<Products> productses) {
		this.brandId = brandId;
		this.name = name;
		this.productses = productses;
	}

	@Id
	@Column(name = "BrandId", unique = true, nullable = false)
	public int getBrandId() {
		return this.brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brands")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
