package entity;


// Generated Mar 1, 2014 7:49:42 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;


/**
 * Cities generated by hbm2java
 */
public class Cities
    implements Serializable
{

    /** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int cityId;
    private Countries countries;
    private String name;
    private Set<Users> userses = new HashSet<Users>(0);


    public Cities()
    {}


    public Cities(int cityId, Countries countries, String name)
    {
        this.cityId = cityId;
        this.countries = countries;
        this.name = name;
    }


    public Cities(int cityId, Countries countries, String name, Set<Users> userses)
    {
        this.cityId = cityId;
        this.countries = countries;
        this.name = name;
        this.userses = userses;
    }


    public int getCityId()
    {
        return this.cityId;
    }


    public void setCityId(int cityId)
    {
        this.cityId = cityId;
    }


    public Countries getCountries()
    {
        return this.countries;
    }


    public void setCountries(Countries countries)
    {
        this.countries = countries;
    }


    public String getName()
    {
        return this.name;
    }


    public void setName(String name)
    {
        this.name = name;
    }


    public Set<Users> getUserses()
    {
        return this.userses;
    }


    public void setUserses(Set<Users> userses)
    {
        this.userses = userses;
    }

}
