package entity;


// Generated Mar 1, 2014 7:49:42 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;


/**
 * Countries generated by hbm2java
 */
public class Countries
    implements Serializable
{

    /** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int countryId;
    private String name;
    private Set<Cities> citieses = new HashSet<Cities>(0);


    public Countries()
    {}


    public Countries(int countryId, String name)
    {
        this.countryId = countryId;
        this.name = name;
    }


    public Countries(int countryId, String name, Set<Cities> citieses)
    {
        this.countryId = countryId;
        this.name = name;
        this.citieses = citieses;
    }


    public int getCountryId()
    {
        return this.countryId;
    }


    public void setCountryId(int countryId)
    {
        this.countryId = countryId;
    }


    public String getName()
    {
        return this.name;
    }


    public void setName(String name)
    {
        this.name = name;
    }


    public Set<Cities> getCitieses()
    {
        return this.citieses;
    }


    public void setCitieses(Set<Cities> citieses)
    {
        this.citieses = citieses;
    }

}
