package entity;


// Generated Mar 1, 2014 7:49:42 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Invoice generated by hbm2java
 */
public class Invoice
    implements java.io.Serializable
{

    /** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int invoiceId;
    private Date dateInvoice;
    private int invoiceNumber;
    private Users customer;
    private Users company;
    private Products product;
    private double quanity;
    private Set<Orders> orderses = new HashSet<Orders>(0);


    public Invoice()
    {}


    public Invoice(int invoiceId, Date dateInvoice, int invoiceNumber)
    {
        this.invoiceId = invoiceId;
        this.dateInvoice = dateInvoice;
        this.invoiceNumber = invoiceNumber;
    }


    public Invoice(Date date, int invoiceNumber, Products pr, Users custemer, Users company, double quantity)
    {
        
        this.dateInvoice = date;
        this.invoiceNumber = invoiceNumber;
        this.product = pr;
        this.company = company;
        this.customer = custemer;
        this.quanity = quantity;
        
       
    }


    public int getInvoiceId()
    {
        return this.invoiceId;
    }


    public void setInvoiceId(int invoiceId)
    {
        this.invoiceId = invoiceId;
    }


    public Date getDateInvoice()
    {
        return this.dateInvoice;
    }


    public void setDateInvoice(Date dateInvoice)
    {
        this.dateInvoice = dateInvoice;
    }


    public int getInvoiceNumber()
    {
        return this.invoiceNumber;
    }


    public void setInvoiceNumber(int invoiceNumber)
    {
        this.invoiceNumber = invoiceNumber;
    }


    public Set<Orders> getOrderses()
    {
        return this.orderses;
    }


    public void setOrderses(Set<Orders> orderses)
    {
        this.orderses = orderses;
    }

}
