package entity;


// Generated Mar 1, 2014 7:49:42 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Payment generated by hbm2java
 */
public class Payment
    implements java.io.Serializable
{

    /** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int paymentId;
    private TypePayment typePayment;
    private Users users;
    private Integer invoiceId;
    private Set<Orders> orderses = new HashSet<Orders>(0);


    public Payment()
    {}


    public Payment(int paymentId, TypePayment typePayment, Users users)
    {
        this.paymentId = paymentId;
        this.typePayment = typePayment;
        this.users = users;
    }


    public Payment(int paymentId,
                   TypePayment typePayment,
                   Users users,
                   Integer invoiceId,
                   Set<Orders> orderses)
    {
        this.paymentId = paymentId;
        this.typePayment = typePayment;
        this.users = users;
        this.invoiceId = invoiceId;
        this.orderses = orderses;
    }


    public int getPaymentId()
    {
        return this.paymentId;
    }


    public void setPaymentId(int paymentId)
    {
        this.paymentId = paymentId;
    }


    public TypePayment getTypePayment()
    {
        return this.typePayment;
    }


    public void setTypePayment(TypePayment typePayment)
    {
        this.typePayment = typePayment;
    }


    public Users getUsers()
    {
        return this.users;
    }


    public void setUsers(Users users)
    {
        this.users = users;
    }


    public Integer getInvoiceId()
    {
        return this.invoiceId;
    }


    public void setInvoiceId(Integer invoiceId)
    {
        this.invoiceId = invoiceId;
    }


    public Set<Orders> getOrderses()
    {
        return this.orderses;
    }


    public void setOrderses(Set<Orders> orderses)
    {
        this.orderses = orderses;
    }

}
