package entity;
// default package
// Generated Feb 26, 2014 5:12:18 PM by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "Products", schema = "dbo", catalog = "warehouseDB1")
public class Products implements Serializable {

	/** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int productId;
	private Categories categories;
	private Brands brands;
	private String  name;
	private double price;
	private double quantity;
	private byte[] image;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Products() {
	}

	public Products(int productId, String  name, double price,
			double quantity) {
		this.productId = productId;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
	}

	public Products(int productId, Categories categories, Brands brands,
			String name, double price, double quantity, byte[] image,
			Set<Orders> orderses) {
		this.productId = productId;
		this.categories = categories;
		this.brands = brands;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.image = image;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
//	@Column(name = "ProductId", unique = true, nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryId")
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BrandId")
	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	@Column(name = "Name", nullable = false)
	public String  getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Price", nullable = false, precision = 53, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "Quantity", nullable = false, precision = 53, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
