package entity;


// Generated Mar 1, 2014 7:49:42 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;


/**
 * UsersGroups generated by hbm2java
 */
public class UsersGroups
    implements Serializable
{

    /** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int usersGroupId;
    private String groupName;
    private Set<Users> userses = new HashSet<Users>(0);


    public UsersGroups()
    {}


    public UsersGroups(int usersGroupId, String groupName)
    {
        this.usersGroupId = usersGroupId;
        this.groupName = groupName;
    }


    public UsersGroups(int usersGroupId, String groupName, Set<Users> userses)
    {
        this.usersGroupId = usersGroupId;
        this.groupName = groupName;
        this.userses = userses;
    }


    public int getUsersGroupId()
    {
        return this.usersGroupId;
    }


    public void setUsersGroupId(int usersGroupId)
    {
        this.usersGroupId = usersGroupId;
    }


    public String getGroupName()
    {
        return this.groupName;
    }


    public void setGroupName(String groupName)
    {
        this.groupName = groupName;
    }


    public Set<Users> getUserses()
    {
        return this.userses;
    }


    public void setUserses(Set<Users> userses)
    {
        this.userses = userses;
    }

}
