package entity;


// Generated Mar 1, 2014 7:49:42 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Users generated by hbm2java
 */
public class Users
    implements Serializable
{

    /** field <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;
    private int userId;
    private UsersGroups usersGroups;
    private Cities cities;
    private String code;
    private String firstName;
    private String lastName;
    private String company;
    private String mol;
    private String address;
    private String address2;
    private String phone;
    private String fax;
    private String email;
    private String taxNo;
    private String bulstat;
    private String bankName;
    private String bankCode;
    private String bankAcct;
    private String bankVatname;
    private String bankVatcode;
    private String bankVatacct;
    private Integer priceGroup;
    private Double discount;
    private Integer type;
    private Integer isVeryUsed;
    private Date userRealTime;
    private Boolean isDeleted;
    private Integer cardNumber;
    private String userName;
    private String password;
    private Set<Orders> orderses = new HashSet<Orders>(0);
    private Set<Payment> payments = new HashSet<Payment>(0);


    public Users()
    {}


    public Users(int userId, String userName, String password)
    {
        this.userId = userId;
        this.userName = userName;
        this.password = password;
    }


    public Users(int userId,
                 UsersGroups usersGroups,
                 Cities cities,
                 String code,
                 String firstName,
                 String lastName,
                 String company,
                 String mol,
                 String address,
                 String address2,
                 String phone,
                 String fax,
                 String email,
                 String taxNo,
                 String bulstat,
                 String bankName,
                 String bankCode,
                 String bankAcct,
                 String bankVatname,
                 String bankVatcode,
                 String bankVatacct,
                 Integer priceGroup,
                 Double discount,
                 Integer type,
                 Integer isVeryUsed,
                 Date userRealTime,
                 Boolean isDeleted,
                 Integer cardNumber,
                 String userName,
                 String password,
                 Set<Orders> orderses,
                 Set<Payment> payments)
    {
        this.userId = userId;
        this.usersGroups = usersGroups;
        this.cities = cities;
        this.code = code;
        this.firstName = firstName;
        this.lastName = lastName;
        this.company = company;
        this.mol = mol;
        this.address = address;
        this.address2 = address2;
        this.phone = phone;
        this.fax = fax;
        this.email = email;
        this.taxNo = taxNo;
        this.bulstat = bulstat;
        this.bankName = bankName;
        this.bankCode = bankCode;
        this.bankAcct = bankAcct;
        this.bankVatname = bankVatname;
        this.bankVatcode = bankVatcode;
        this.bankVatacct = bankVatacct;
        this.priceGroup = priceGroup;
        this.discount = discount;
        this.type = type;
        this.isVeryUsed = isVeryUsed;
        this.userRealTime = userRealTime;
        this.isDeleted = isDeleted;
        this.cardNumber = cardNumber;
        this.userName = userName;
        this.password = password;
        this.orderses = orderses;
        this.payments = payments;
    }


    public int getUserId()
    {
        return this.userId;
    }


    public void setUserId(int userId)
    {
        this.userId = userId;
    }


    public UsersGroups getUsersGroups()
    {
        return this.usersGroups;
    }


    public void setUsersGroups(UsersGroups usersGroups)
    {
        this.usersGroups = usersGroups;
    }


    public Cities getCities()
    {
        return this.cities;
    }


    public void setCities(Cities cities)
    {
        this.cities = cities;
    }


    public String getCode()
    {
        return this.code;
    }


    public void setCode(String code)
    {
        this.code = code;
    }


    public String getFirstName()
    {
        return this.firstName;
    }


    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }


    public String getLastName()
    {
        return this.lastName;
    }


    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }


    public String getCompany()
    {
        return this.company;
    }


    public void setCompany(String company)
    {
        this.company = company;
    }


    public String getMol()
    {
        return this.mol;
    }


    public void setMol(String mol)
    {
        this.mol = mol;
    }


    public String getAddress()
    {
        return this.address;
    }


    public void setAddress(String address)
    {
        this.address = address;
    }


    public String getAddress2()
    {
        return this.address2;
    }


    public void setAddress2(String address2)
    {
        this.address2 = address2;
    }


    public String getPhone()
    {
        return this.phone;
    }


    public void setPhone(String phone)
    {
        this.phone = phone;
    }


    public String getFax()
    {
        return this.fax;
    }


    public void setFax(String fax)
    {
        this.fax = fax;
    }


    public String getEmail()
    {
        return this.email;
    }


    public void setEmail(String email)
    {
        this.email = email;
    }


    public String getTaxNo()
    {
        return this.taxNo;
    }


    public void setTaxNo(String taxNo)
    {
        this.taxNo = taxNo;
    }


    public String getBulstat()
    {
        return this.bulstat;
    }


    public void setBulstat(String bulstat)
    {
        this.bulstat = bulstat;
    }


    public String getBankName()
    {
        return this.bankName;
    }


    public void setBankName(String bankName)
    {
        this.bankName = bankName;
    }


    public String getBankCode()
    {
        return this.bankCode;
    }


    public void setBankCode(String bankCode)
    {
        this.bankCode = bankCode;
    }


    public String getBankAcct()
    {
        return this.bankAcct;
    }


    public void setBankAcct(String bankAcct)
    {
        this.bankAcct = bankAcct;
    }


    public String getBankVatname()
    {
        return this.bankVatname;
    }


    public void setBankVatname(String bankVatname)
    {
        this.bankVatname = bankVatname;
    }


    public String getBankVatcode()
    {
        return this.bankVatcode;
    }


    public void setBankVatcode(String bankVatcode)
    {
        this.bankVatcode = bankVatcode;
    }


    public String getBankVatacct()
    {
        return this.bankVatacct;
    }


    public void setBankVatacct(String bankVatacct)
    {
        this.bankVatacct = bankVatacct;
    }


    public Integer getPriceGroup()
    {
        return this.priceGroup;
    }


    public void setPriceGroup(Integer priceGroup)
    {
        this.priceGroup = priceGroup;
    }


    public Double getDiscount()
    {
        return this.discount;
    }


    public void setDiscount(Double discount)
    {
        this.discount = discount;
    }


    public Integer getType()
    {
        return this.type;
    }


    public void setType(Integer type)
    {
        this.type = type;
    }


    public Integer getIsVeryUsed()
    {
        return this.isVeryUsed;
    }


    public void setIsVeryUsed(Integer isVeryUsed)
    {
        this.isVeryUsed = isVeryUsed;
    }


    public Date getUserRealTime()
    {
        return this.userRealTime;
    }


    public void setUserRealTime(Date userRealTime)
    {
        this.userRealTime = userRealTime;
    }


    public Boolean getIsDeleted()
    {
        return this.isDeleted;
    }


    public void setIsDeleted(Boolean isDeleted)
    {
        this.isDeleted = isDeleted;
    }


    public Integer getCardNumber()
    {
        return this.cardNumber;
    }


    public void setCardNumber(Integer cardNumber)
    {
        this.cardNumber = cardNumber;
    }


    public String getUserName()
    {
        return this.userName;
    }


    public void setUserName(String userName)
    {
        this.userName = userName;
    }


    public String getPassword()
    {
        return this.password;
    }


    public void setPassword(String password)
    {
        this.password = password;
    }


    public Set<Orders> getOrderses()
    {
        return this.orderses;
    }


    public void setOrderses(Set<Orders> orderses)
    {
        this.orderses = orderses;
    }


    public Set<Payment> getPayments()
    {
        return this.payments;
    }


    public void setPayments(Set<Payment> payments)
    {
        this.payments = payments;
    }

}
